fga-eps-mds/2020.1-VC_Usuario

- CODE_OF_CONDUCT.md
#4 Inserindo documento de código de conduta no repositório
> #4 Criando documento de codigo de conduta

- CODE_OF_CONDUCT.md
#4 Modificação dos tópicos de "Exemplos de comportamentos esperados e que contribuem com o projeto" e "Exemplos de comportamentos inaceitáveis"
> #4 Modificando documento de codigo de Conduta

- CONTRIBUTING.md
#4 Criação de arquivo de Contribuição
> #4 Criando arquivo CONTRIBUTING.md

- CONTRIBUTING.md
Alterando o arquivo CONTRIBUTING.MD
#4
> Modificando arquivo CONTRIBUTING.MD

- docs/Documento_de_arquitetura.md
Criei esse template de documento de arquitetura de software já com algumas informações relacionadas ao projeto.
#24 
Documento necessário para o bom andamento do projeto.
existentes)
> #24 Inserindo documento de arquitetura

- docs/Documento_de_Visao.md
Inserindo o item 2.2 no Documento de Visão
#41 
Desenvolvimento do Documento de Visão do Projeto
> #41 Inserindo o item 2.2 no Documento de Visão

- docs/Documento_de_Visao.md
Adicionando os tópicos 1, 1.1 e 1.2
#41 
Desenvolvimento do Documento de Visão do Projeto
> #41 Inserindo os itens 1, 1.1, 1.2 no Documento de Visão

- docs/Documento_de_Visao.md
Adicionando os tópicos 3.1, 3.2, 3.3 e 3.4.
#41 
Desenvolvimento do Documento de Visão do Projeto.
Não necessita de testes.
> #41 Inserindo os itens 3.1, 3.2, 3.3 e 3.4 no Documento de Visão

- docs/Documento_de_Visao.md
Atualização do Histórico de Revisão do Documento de Visão - 0.6, Inserção dos itens 3.1, 3.2, 3.3 e 3.4, Enzo Gabriel
#41 
Aceitei um pull request do @enzoggqs sem perceber que faltava atualizar o histórico de Revisão com os incrementos feito por ele.
É um documento, não precisa ser testado
> #41 Atualizando Histórico de Revisão - 0.6 Enzo Gabriel

- docs/Documento_de_Visao.md
Inserindo os itens 2.1 e 2.3 no Documento de Visão.
#41 
Desenvolvimento do Documento de Visão do Projeto.
> #41 Inserindo os itens 2.1 e 2.3 no Documento de Visão

- docs/Roadmap.md
Criando o template do Roadmap
#45 
Ela cria o template do Roadmap do produto.
> #45 Adicionando o template do Roadmap

- docs/Documento_de_Visao.md
Inserindo os itens 1.3 e 1.4 no documento de visão
#41
Desenvolvimento do Documento de Visão do Projeto.
> #41 Inserindo os itens 1.3 e 1.4 no documento de visão

- docs/Plano_riscos.md
Adicionando o Documento do Plano de Riscos
#56 
Desenvolvimento do Documento do Plano de Riscos do Projeto
> #56 adicionando documento do plano de riscos

- README.md
- docs/Documento_de_Visao.md
- docs/Product_Backlog.md
Criando documento e desenvolvendo Product Backlog: Tópicos 1, 2 e 3;
Formatando Documento de Visão: Alinhamento e Recuo.
#58 #59
Desenvolvimento e conclusão dessas documentações
São documentos, não precisa ser testado.
> #58 #59 Desenvolvendo Product Backlog e Formatando Documento de Visão

- docs/Product_Backlog.md
Adicionando pontuação nas Histórias de Usuário do Product Backlog
Pontuação era a unica parte do documento que faltava, mas precisava de todos juntos para ser realizada. 
É um documento, não precisa ser testado.
> #58 Adicionando pontuação nas Histórias de Usuário do Product Backlog

- docs/policies/branches.md
- docs/policies/commits.md
- docs/policies/issues.md
- docs/policies/policies.md
- docs/policies/pull_request.md
Inclusão dos documentos das políticas para a contribuição com o projeto
#62 
Para ficar documentado como a contribuição deve acontecer
É um documento, não precisa de testes
> #62 incluindo os documentos de políticas para contribuição

- docs/Documento_de_arquitetura.md
- docs/pull_request_template.md
Foi adicionado o template de pull request a branch develop e adicionado os requisitos ao documento de arquitetura
#62 e #64 
É necessário para a documentação do projeto
Não precisa de testes, são documentos
> #62 Adicionando o template de pull request a branch develop e #64 adicionando os requisitos ao documento de arquitetura

- docs/sprints/sprint_0/Planning_Sprint_0.md
- docs/sprints/sprint_0/Review_Sprint_0.md
- docs/sprints/sprint_1/Planning_Sprint_1.md
- docs/sprints/sprint_1/Review_Sprint_1.md
- docs/sprints/sprint_2/Planning_Sprint_2.md
- docs/sprints/sprint_2/Review_Planning_2.md
Adicionando Planning e Review das Sprints 0, 1 e 2.
#57 
Documentação das Sprints do projeto.
> #57 Adicionando Planning e Review das Sprints 0, 1 e 2

- docs/Documento_de_Visao.md
Revisando e desenvolvendo todos os tópicos do Documento de Visão
#59 
Finalizar o Documento de Visão, documento muito importante como o projeto e para o produto.
> #59 Revisando e desenvolvendo todo o documento - Documento de Visão

- .github/pull_request_template.md
- docker-compose.yml
- docs/Documento_de_Visao.md
- docs/Product_Backlog.md
- Revisão do Product Backlog com a nova visão do produto;
- Atualização dos Requisitos;
- Configurando do nome do container do docker-compose.
- Inserindo opção Documentação - Template Pull Request
#90 #73
Era importantíssimo para o planejamento e desenvolvimento do projeto.
Era um documento, não precisava ser testada.
> #90 #73 Revisão do Product Backlog, Configurando docker-compose e Adição template PR

- docs/Roadmap.md
Foram feitas algumas alterações no documento de Roadmap.
#86 
Foi feita para resolver alguns problemas que estavam presentes no documento.
> #86 Refatorando Roadmap

- .github/pull_request_template.md
- docker-compose.yml
- docs/Documento_de_Visao.md
- docs/Product_Backlog.md
Reverts fga-eps-mds/2020.1-VC_Usuario#99
> Revert "#90 #73 Revisão do Product Backlog, Configurando docker-compose e Adição template PR"

- .github/pull_request_template.md
- Makefile
- docker-compose.yml
- docs/Documento_de_Visao.md
- docs/Product_Backlog.md
- src/index.js
- Revisando Product Backlog;
- Configurando docker-compose
#90 #72
Product Backlog precisa ser ajustado a nova visão do produto;
Ajustando o docker-compose para ser usando junto ao MongoDB.
Teste de ambiente foram feitos para validar o funcionamento do mongodb.
> #90 #72 Revisando Product Backlog e Configurando docker-compose

- docs/Roadmap.md
Co-authored-by: Enzo Gabriel <eggqsaraiva@gmail.com>
Foram feitas alterações nas programações do roadmap.
#86
> #86 Revisando o Roadmap

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- README.md redireciona para o CONTRIBUTING da pagina de documentação;
- CONTRIBUTING, CODE_OF_CONDUCT da develop foram atualizados.
#129 
Não se aplica.
> Atualizando CONTRIBUTING, CODE_OF_CONDUCT da develop.

- _sidebar.md
- docs/Canvas.md
- docs/Documento_de_Arquitetura.md
- docs/Documento_de_Visao.md
- docs/Plano_riscos.md
- docs/Prototipos.md
- style/css/general.css
Revisão das documentações
#129 
> 129 feedback documentacao

- docs/Roadmap.md
Foi atualizada a sprint 7 no roadmap
#135 
É um documento, não precisa de teste
> #135 Atualizando o roadmap

- README.md
Foi adicionado o Maintainability ao readme com o code climate
#141 
É um documento, não precisa de teste
> #141 adicionando code climate ao readme

- package-lock.json
- package.json
- src/config/auth.json
- src/controllers/auth_controller.js
- src/controllers/user_controller.js
- src/models/user.js
- src/routes.js
Foram corrigidos alguns erros de retornos, criado método para atualização de tokens e uma rota para validação de sessão.
#130 
Os testes foram feitos pelo Insomnia e pelo navegador.
> US06 #130 fazer/desfazer login

- src/controllers/user_controller.js
- src/models/postage.js
- src/models/user.js
- src/routes.js
Foi criada uma rota para filtrar os usuários pelo seu ID e Adicionado o aturo da postagem na model de postagens
#136 
Os testes foram feitos com o insomnia
> US07 #136 Postagem Logado

- src/controllers/auth_controller.js
- src/controllers/user_controller.js
- src/models/user.js
- src/routes.js
Foi feito a US de editar e excluir conta do usuário
#154  #155
Pelo browser e pelo insomnia
> Feature/us13 us14 #154 excluir/#155 editar conta

- src/controllers/postage_controller.js
Quando o usuário está logado, a listagem é feita com todas as postagens, sendo elas anonimas ou não.
PR destinado a somente listar as postagens não anonimas no feed quando logado.
#169
Usando a listagem na home e a ferramenta Insomnia;
> #169 Listando Postagens Logado

- src/controllers/postage_controller.js
- src/routes.js
Foi feito a filtragem das postagens na página home
#161 
Pelo browser do mozilla
> Feature/us15 #161 filtrar postagens

- src/controllers/UPS_controller.js
- src/controllers/postage_controller.js
- src/index.js
- src/routes.js
- Funcionalidade de o usuário Editar Postagem;
- Funcionalidade de o usuário Excluir Postagem;
- Padronizando mensagem de erro das controller postage e UPS.
#166
Usando o console do terminal e a ferramenta Insomnia.
> US11 US12 #166 Excluir e Editar Postagem

- src/controllers/UPS_controller.js
- Retirada da inserção e remoção da UPS do array de UPSs do User;
- Retirada da verificação se UPS foi devidamente removida ou não;
- Afinamento e refatoração do código.
---
- Número de linhas de código do método menor ou igual a 25 linhas (Era 40 linhas);
- Complexidade do código menor ou igual a 5 (Era 13 de complexidade).
#181
Usando a ferramenta Insomnia, console do terminal e a própria aplicação.
> #181 Issues do Code Climate em support_postage

- src/controllers/postage_controller.js
- src/routes.js
Issue destinada a resolver a issue do Code Climate de duplicação na inserção do file na postagem.
#178
Usando a ferramenta Insomnia, console do terminal e a aplicação(backend + frontend)
> #178 Issue de duplicação de código do Code Climate

- .env
- Procfile
- src/controllers/postage_controller.js
- src/index.js
Fazendo o deploy do backend
#174 
Com o heroku e com o lindo do deploy https://vc-usuario-backend.herokuapp.com
> 174 implementar deploy

- src/controllers/postage_controller.js
- src/controllers/user_controller.js
- src/routes.js
- Quando não há um usuário logado a postagem não mostra a categoria no component postagem na página Home;
- A página do Perfil não monstra as ups das postagens.
#195
Pelo console.log do navegador, pelo Insomnia, pelo console do terminal e pela própria aplicação
> #195 Bug de Listagens

- src/controllers/postage_controller.js
… o mesmo do fk_user_id da postagem - postage_controller
- Arrumando erro na verificação de que o user_id da requisição ser o mesmo do fk_user_id da postagem - postage_controller
Através dos console.log do terminal e da própria a aplicação.
> #195 Arrumando erro no método check_user_of_postage

- src/controllers/UPC_controller.js
- src/controllers/UPS_controller.js
- src/controllers/auth_controller.js
- src/controllers/postage_controller.js
- src/controllers/user_controller.js
- src/index.js
- src/models/UPC.js
- src/models/postage.js
- src/models/user.js
- src/routes.js
Foi arrumado alguns bugs do backend listados
#197 
Com o insomnia e com o browser
> 197 arrumando bugs backend

- src/controllers/UPC_controller.js
- src/controllers/postage_controller.js
- src/models/UPC.js
- src/routes.js
Pull Request destinado ao a listagem das postagens.
#192
Usando o Insominia, o console.log do terminal e a própria aplicação.
> US22 #192 Usuario Logado Comentar Postagem

- src/controllers/UPR_controller.js
- src/controllers/postage_controller.js
- src/models/UPR.js
- src/models/postage.js
- src/routes.js
Pull Request destinado ao usuário logado poder fazer denúncia de postagens
#199 
Pelo Insomnia e pela própria aplicação
quanto tento reportar mais de uma vez:
> US20 #199 Denunciar Postagem

- src/controllers/postage_controller.js
- Mudanças de status da postagem para Em Andamento e Arquivado dá erro.
#216
Pelo Insomnia e pela própria aplicação.
):
> #216 Resolvendo bug de atualizar status da postagem
